SET NAMES utf8mb4;

INSERT INTO `menu_tree` (`menu_name`, `mlid`, `id`, `parent`, `route_name`, `route_param_key`, `route_parameters`, `url`, `title`, `description`, `class`, `options`, `provider`, `enabled`, `discovered`, `expanded`, `weight`, `metadata`, `has_children`, `depth`, `p1`, `p2`, `p3`, `p4`, `p5`, `p6`, `p7`, `p8`, `p9`, `form_class`) VALUES
('admin',	246,	'entity.feeds_feed_type.edit_form.offers',	'',	'entity.feeds_feed_type.edit_form',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	's:16:\"Вариации\";',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	0,	'a:0:{}',	1,	1,	246,	0,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	247,	'entity.feeds_feed.field_ui_fieldsoffers',	'entity.feeds_feed_type.edit_form.offers',	'entity.feeds_feed.field_ui_fields',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:13:\"Manage fields\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	1,	'a:0:{}',	0,	2,	246,	247,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	248,	'entity.entity_form_display.feeds_feed.defaultoffers',	'entity.feeds_feed_type.edit_form.offers',	'entity.entity_form_display.feeds_feed.default',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:19:\"Manage form display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	2,	'a:0:{}',	0,	2,	246,	248,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	249,	'entity.entity_view_display.feeds_feed.default.offers',	'entity.feeds_feed_type.edit_form.offers',	'entity.entity_view_display.feeds_feed.default',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:14:\"Manage display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	3,	'a:0:{}',	0,	2,	246,	249,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	250,	'entity.feeds_feed_type.devel_load.offers',	'entity.feeds_feed_type.edit_form.offers',	'entity.feeds_feed_type.devel_load',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:5:\"Devel\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	4,	'a:0:{}',	0,	2,	246,	250,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	251,	'entity.feeds_feed_type.delete_form.offers',	'entity.feeds_feed_type.edit_form.offers',	'entity.feeds_feed_type.delete_form',	'feeds_feed_type=offers',	'a:1:{s:15:\"feeds_feed_type\";s:6:\"offers\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:6:\"Delete\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	5,	'a:0:{}',	0,	2,	246,	251,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	252,	'entity.feeds_feed_type.edit_form.tovar',	'',	'entity.feeds_feed_type.edit_form',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	's:12:\"Товары\";',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	0,	'a:0:{}',	1,	1,	252,	0,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	253,	'entity.feeds_feed.field_ui_fieldstovar',	'entity.feeds_feed_type.edit_form.tovar',	'entity.feeds_feed.field_ui_fields',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:13:\"Manage fields\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	1,	'a:0:{}',	0,	2,	252,	253,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	254,	'entity.entity_form_display.feeds_feed.defaulttovar',	'entity.feeds_feed_type.edit_form.tovar',	'entity.entity_form_display.feeds_feed.default',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:19:\"Manage form display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	2,	'a:0:{}',	0,	2,	252,	254,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	255,	'entity.entity_view_display.feeds_feed.default.tovar',	'entity.feeds_feed_type.edit_form.tovar',	'entity.entity_view_display.feeds_feed.default',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:14:\"Manage display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	3,	'a:0:{}',	0,	2,	252,	255,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	256,	'entity.feeds_feed_type.devel_load.tovar',	'entity.feeds_feed_type.edit_form.tovar',	'entity.feeds_feed_type.devel_load',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:5:\"Devel\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	4,	'a:0:{}',	0,	2,	252,	256,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	257,	'entity.feeds_feed_type.delete_form.tovar',	'entity.feeds_feed_type.edit_form.tovar',	'entity.feeds_feed_type.delete_form',	'feeds_feed_type=tovar',	'a:1:{s:15:\"feeds_feed_type\";s:5:\"tovar\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:6:\"Delete\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	5,	'a:0:{}',	0,	2,	252,	257,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	258,	'entity.feeds_feed_type.edit_form.catalog',	'',	'entity.feeds_feed_type.edit_form',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	's:14:\"Каталог\";',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	0,	'a:0:{}',	1,	1,	258,	0,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	259,	'entity.feeds_feed.field_ui_fieldscatalog',	'entity.feeds_feed_type.edit_form.catalog',	'entity.feeds_feed.field_ui_fields',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:13:\"Manage fields\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	1,	'a:0:{}',	0,	2,	258,	259,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	260,	'entity.entity_form_display.feeds_feed.defaultcatalog',	'entity.feeds_feed_type.edit_form.catalog',	'entity.entity_form_display.feeds_feed.default',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:19:\"Manage form display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	2,	'a:0:{}',	0,	2,	258,	260,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	261,	'entity.entity_view_display.feeds_feed.default.catalog',	'entity.feeds_feed_type.edit_form.catalog',	'entity.entity_view_display.feeds_feed.default',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:14:\"Manage display\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	3,	'a:0:{}',	0,	2,	258,	261,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	262,	'entity.feeds_feed_type.devel_load.catalog',	'entity.feeds_feed_type.edit_form.catalog',	'entity.feeds_feed_type.devel_load',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:5:\"Devel\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	4,	'a:0:{}',	0,	2,	258,	262,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm'),
('admin',	263,	'entity.feeds_feed_type.delete_form.catalog',	'entity.feeds_feed_type.edit_form.catalog',	'entity.feeds_feed_type.delete_form',	'feeds_feed_type=catalog',	'a:1:{s:15:\"feeds_feed_type\";s:7:\"catalog\";}',	'',	'O:48:\"Drupal\\Core\\StringTranslation\\TranslatableMarkup\":3:{s:9:\"\0*\0string\";s:6:\"Delete\";s:12:\"\0*\0arguments\";a:0:{}s:10:\"\0*\0options\";a:0:{}}',	's:0:\"\";',	'Drupal\\Core\\Menu\\MenuLinkDefault',	'a:0:{}',	'',	1,	1,	0,	5,	'a:0:{}',	0,	2,	258,	263,	0,	0,	0,	0,	0,	0,	0,	'Drupal\\Core\\Menu\\Form\\MenuLinkDefaultForm');
